name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.8
        # File containing the Python version to use. Example: .python-version
    - name: Intall requirements
      run: pip3 install -r requirements_linux.txt
    - name: Start build with PyInstaller
      run: pip3 install pyinstaller && pyinstaller -D -F -n main -c "main.py"
    - name: Upload Artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: .

  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          requirements: requirements_windows.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: .

  build_macos:
    name: Build MacOS
    runs-on: macos-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            
      - name: Install Dependencies
        run: |
          pip install -r requirements_macos.txt 
          
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          onefile: true
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS Build
          path: |
            build
